### ISSUE TITLE
Failed to load AsciiDoc document - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by duesentrieb17** [de-jcup/eclipse-asciidoctor-editor#138]
A file with the encoding Cp1252  and a German umlaut (see file in [test.zip](https://github.com/de-jcup/eclipse-asciidoctor-editor/files/2293350/test.zip)) causes the following exception:
```
eclipse.buildId=4.7.3.M20180330-0640
java.version=10.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -showLocation -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -showLocation -clean -product org.eclipse.epp.package.rcp.product

de.jcup.asciidoctoreditor
Error
Thu Aug 16 12:24:45 CEST 2018
AsciiDoctor error occured:org.jruby.exceptions.RaiseException: (ArgumentError) asciidoctor: FAILED: D:/test.adoc: Failed to load AsciiDoc document - invalid byte sequence in UTF-8

org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (ArgumentError) asciidoctor: FAILED: D:/test.adoc: Failed to load AsciiDoc document - invalid byte sequence in UTF-8
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:347)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:551)
	at de.jcup.asciidoctoreditor.AsciiDoctorWrapper.convertToHTML(AsciiDoctorWrapper.java:70)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor.fullBuildTemporaryHTMLFilesAndShowAfter(AsciiDoctorEditor.java:667)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor.access$8(AsciiDoctorEditor.java:640)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor$1.run(AsciiDoctorEditor.java:889)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:182)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jruby.exceptions.RaiseException: (ArgumentError) asciidoctor: FAILED: D:/test.adoc: Failed to load AsciiDoc document - invalid byte sequence in UTF-8
	at org.jruby.RubyString.rstrip!(org/jruby/RubyString.java:6007)
	at org.jruby.RubyString.rstrip(org/jruby/RubyString.java:5995)
	at Module.normalize_lines_array(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/helpers.rb:80)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at Module.normalize_lines_array(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/helpers.rb:80)
	at Asciidoctor::Reader.prepare_lines(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:94)
	at Asciidoctor::PreprocessorReader.prepare_lines(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:582)
	at Asciidoctor::Reader.initialize(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:65)
	at Asciidoctor::PreprocessorReader.initialize(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:569)
	at RUBY.initialize(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:463)
	at Module.load(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1341)
	at RUBY.convert(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1457)
	at RUBY.convert_file(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1201)
	at RUBY.convert_file(C:/Users/bw1kang0/.eclipse-asciidoctor-editor/libs/1.2.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575)
	at RUBY.convertFile(<script>:75)
	at org.jruby.gen.InterfaceImpl261913477.convertFile(org/jruby/gen/InterfaceImpl261913477.gen:13)

```

**Comment by de-jcup** [comment]
ASCII doc Files must be UTF-8. Please Set those folders top UTF-8 and
convert content.

See https://asciidoctor.org/docs/user-manual/



duesentrieb17 <notifications@github.com> schrieb am Do., 16. Aug. 2018,
12:36:
