### ISSUE TITLE
Problems with non-ASCII characters and scrolling

### ISSUE THREAD

**Issue by mschaufelberger** [de-jcup/eclipse-asciidoctor-editor#177]
Minimal example:
```
= My Title

== My Section

```
There's a very cool feature that if I move the cursor to `My Section` the preview also scrolls to that section. Unfortunately this only works as long as I don't use umlauts or other non-ASCII characters.

If I change `Section` to `Sectiön` the scrolling does not work anymore and with big documents it already happened to me that a "Abnormal Workbench Condition" popup occurred (in Eclipse's "Error Log" view there were various "Unhandled event loop exception" and "Problems occured when invoking code from plug-in: "org.eclipse.text"").

With the minimal example I can find the following error event in the "Error Log" view everytime I move the cursor to `My Sectiön`:
```
Was not able to execute javascript:document.getElementById('_my_secti_n').scrollIntoView();
```
(Stack trace see below)

If this is complicated to fix it would be nice to have an option to disable the scrolling feature in the preferences, as a workaround to avoid workbench crashes.

Exception Stack Trace:
```
org.eclipse.swt.SWTException: Unable to get property 'scrollIntoView' of undefined or null reference
	at org.eclipse.swt.browser.WebBrowser$EvaluateFunction.function(WebBrowser.java:195)
	at org.eclipse.swt.browser.WebSite.Invoke(WebSite.java:829)
	at org.eclipse.swt.browser.WebSite$7.method6(WebSite.java:187)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(COMObject.java:122)
	at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
	at org.eclipse.swt.internal.ole.win32.IDispatch.Invoke(IDispatch.java:68)
	at org.eclipse.swt.ole.win32.OleAutomation.invoke(OleAutomation.java:575)
	at org.eclipse.swt.ole.win32.OleAutomation.invoke(OleAutomation.java:538)
	at org.eclipse.swt.browser.IE.execute(IE.java:1202)
	at org.eclipse.swt.browser.WebBrowser.nonBlockingExecute(WebBrowser.java:400)
	at org.eclipse.swt.browser.WebBrowser.evaluate(WebBrowser.java:450)
	at org.eclipse.swt.browser.WebBrowser.evaluate(WebBrowser.java:406)
	at org.eclipse.swt.browser.Browser.evaluate(Browser.java:683)
	at org.eclipse.swt.browser.Browser.evaluate(Browser.java:630)
	at de.jcup.asciidoctoreditor.BrowserAccess$3.run(BrowserAccess.java:130)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
```

**Comment by de-jcup** [comment]
Hello @mschaufelberger . Do you use `UTF-8` as encoding used by eclipse when using umlauts? 
AsciiDoctor wants this explicit and maybe the id fetching makes also here some problems.
Please check you encoding type by opening `Properties` of your asciidoc file.

Just to ensure I can reproduce your problem.

**Comment by mschaufelberger** [comment]
Hi @de-jcup 
Yes, we use `UTF-8` in all files and I double-checked it for the test file I created to reproduce the problem.

I'm using version 1.2.0 of Asciidoctor Editor and version 4.10.0 of the Eclipse SDK/Platform.

**Comment by mschaufelberger** [comment]
Hi @de-jcup, thanks for the fast fix! However I would like to suggest a solution that might avoid further problems with other languages: You could try to use this pattern instead (in `AsciiDoctorHeadline.java`) to also keep other letters like ñ, è, â, ø etc. while still replacing non-letters like ®, ¼, €, ...
```java
private static final String REGEXP_STRING = "\\W";
private static final Pattern REGEXP= Pattern.compile(REGEXP_STRING, Pattern.UNICODE_CHARACTER_CLASS);
```
If you prefer to keep the negated character class you might of course also use `"[^\\w]"` instead of `"\\W"` as `REGEXP_STRING`.

**Comment by de-jcup** [comment]
@mschaufelberger Thank you. I have changed it in last commit as you suggested. Much better :+1:
