### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by StefanHirche** [de-jcup/eclipse-asciidoctor-editor#208]
When I open a doc in the AsciiDoctor Editor, I get an error in the first line stating:
NoSuchMethodError: org.apache.commons.io.FileUtils.writeStringToFile(Ljava/io/File;Ljava/lang/String;Ljava/lang/String;Z)V

I know that this method is removed in recent releases of Apache Commons. Is it somehow possible to influence the version used by AsciiDoctor Editor?

So the result of this error is that the HTML is not rendered and after some time, the browser says "Preview file generation timed out, so preview not available."

**Comment by de-jcup** [comment]
Please open ErrorLog view and look for the complete error. Then add the stacktrace here.

Please also answer following  questions:
- Which editor version do you use ?
- Which Java version do you use to start eclipse?
- Which eclipse Version do you use?

commons io lib is distributed with asciidoctor editor. But maybe eclipse version (has commons io also inside) is used by classpath.

**Comment by StefanHirche** [comment]
Hi.
First, the trace:
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.writeStringToFile(Ljava/io/File;Ljava/lang/String;Ljava/lang/String;Z)V
	at de.jcup.asciidoctoreditor.AsciiDocFileUtils.createHiddenEditorFile(AsciiDocFileUtils.java:120)
	at de.jcup.asciidoctoreditor.AsciiDoctorWrapper.convertToHTML(AsciiDoctorWrapper.java:74)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditorBuildSupport.fullBuildTemporaryHTMLFilesAndShowAfter(AsciiDoctorEditorBuildSupport.java:193)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditorBuildSupport.access$0(AsciiDoctorEditorBuildSupport.java:151)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditorBuildSupport$1.run(AsciiDoctorEditorBuildSupport.java:118)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by StefanHirche** [comment]
I use version 1.4.4 of the editor
Java Version is 11.0.1
Eclipse Version: 2019-03 (4.11.0)
Build id: 20190314-1200

**Comment by de-jcup** [comment]
Hm... I am also using Eclipse 2019-03 but have not such errror. Please do me a favour and start your eclipse with JDK8.
see https://wiki.eclipse.org/Eclipse.ini#Specifying_the_JVM for details about setting used JDK8

Would be nice to have information if this is a problem because of JVM or not.

**Comment by StefanHirche** [comment]
OK, tried to use Java 1.8.0_181 but got the same issue.

**Comment by de-jcup** [comment]
Hmm... i provide the library by my lib plugin. But you are (at least currently) the only one having such a problem with the plugin.

What OS are you using ?

**Comment by StefanHirche** [comment]
Windows 10.

Albert Tregnaghi <notifications@github.com> schrieb am Di., 21. Mai 2019
10:02:
