### ISSUE TITLE
Lib plugin does not contain asp server

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#225]
Whith 2.0.0.alpha2 standalone release currently ASP server is not included. Must be fixed before going beta/final.

**Comment by de-jcup** [comment]
Currently we got a NPE (will be changed with 
```
...
Caused by: java.lang.NullPointerException
	at de.jcup.asciidoctoreditor.PluginContentInstaller.copyFolderOrFail(PluginContentInstaller.java:132)
	at de.jcup.asciidoctoreditor.PluginContentInstaller.ensureServerArtefactsAreAvailable(PluginContentInstaller.java:103)
	at de.jcup.asciidoctoreditor.PluginContentInstaller.getASPFolder(PluginContentInstaller.java:51)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditorActivator.updateASPServerStart(AsciiDoctorEditorActivator.java:89)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditorActivator.start(AsciiDoctorEditorActivator.java:74)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:815)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:808)
	... 150 more
```
With https://github.com/de-jcup/eclipse-commons/issues/27 the NPE will be replaced in future by a dedicated IO exception, but the problem exists: Lib does not contain ASP server.
