### ISSUE TITLE
NPE on opening a plant-uml file by hyperlink

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#235]
```
java.lang.NullPointerException
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor.rebuild(AsciiDoctorEditor.java:546)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport$RevalidateAfterBuildListener.buildDone(AsciiDoctorEditorBuildSupport.java:412)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport$1.run(AsciiDoctorEditorBuildSupport.java:153)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by de-jcup** [comment]
Problems is that rebuild action does not exist for plantuml editor and also not for ditaa editor.

Also it is a little bit strange hat this was exeucted by revalidate action on `AsciiDoctorEditorBuildSupport`
