### ISSUE TITLE
The version 2.0.0 is not able to render the preview.

### ISSUE THREAD

**Issue by charleech** [de-jcup/eclipse-asciidoctor-editor#248]
I've just updated to the version `2.0.0` and found that the preview is not rendered as

```
Preview file generation timed out, so preview not available at: 
\AppData\Local\Temp\asciidoctor-editor-temp\<project>-1001799199\-1004703556_internal_hello.html
```

* The `hello.adoc` has been taken from https://asciidoctor.org/docs/asciidoc-article/

* The `\AppData\Local\Temp\asciidoctor-editor-temp\<project>-1001799199\-1004703556_hidden-editorfile_hello.adoc`

```
// origin :path\to\hello.adoc
// editor :-1004703556
// basedir:path\to
include::hello.adoc[]
```

* [Workspace]/.metadata/.log

```
!ENTRY de.jcup.asciidoctoreditor 4 0 2019-07-09 09:39:16.441
!MESSAGE Cannot convert to html:path\to\hello.adoc
!STACK 0
java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 24
	at java.util.Base64$Decoder.decode0(Base64.java:742)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at de.jcup.asp.core.CryptoAccess.<init>(CryptoAccess.java:44)
	at de.jcup.asp.client.AspClient.<init>(AspClient.java:61)
	at de.jcup.asciidoctoreditor.asciidoc.ASPServerAdapter.startServer(ASPServerAdapter.java:124)
	at de.jcup.asciidoctoreditor.ASPSupport$FallbackRestartHandler.handleNotAvailable(ASPSupport.java:34)
	at de.jcup.asciidoctoreditor.ASPSupport.waitForServerAvailable(ASPSupport.java:60)
	at de.jcup.asciidoctoreditor.ASPSupport.getAspClient(ASPSupport.java:19)
	at de.jcup.asciidoctoreditor.asciidoc.AspAsciidoctorAdapter.resolveClient(AspAsciidoctorAdapter.java:68)
	at de.jcup.asciidoctoreditor.asciidoc.AspAsciidoctorAdapter.convertFile(AspAsciidoctorAdapter.java:50)
	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.convert(AsciiDoctorWrapper.java:76)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport.fullBuildTemporaryHTMLFilesAndShowAfter(AsciiDoctorEditorBuildSupport.java:219)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport.access$1(AsciiDoctorEditorBuildSupport.java:174)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport$1.run(AsciiDoctorEditorBuildSupport.java:138)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY de.jcup.asciidoctoreditor 4 0 2019-07-09 09:39:16.457
!MESSAGE AsciiDoctor error occured:Input byte array has incorrect ending byte at 24
!STACK 0
java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 24
	at java.util.Base64$Decoder.decode0(Base64.java:742)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at de.jcup.asp.core.CryptoAccess.<init>(CryptoAccess.java:44)
	at de.jcup.asp.client.AspClient.<init>(AspClient.java:61)
	at de.jcup.asciidoctoreditor.asciidoc.ASPServerAdapter.startServer(ASPServerAdapter.java:124)
	at de.jcup.asciidoctoreditor.ASPSupport$FallbackRestartHandler.handleNotAvailable(ASPSupport.java:34)
	at de.jcup.asciidoctoreditor.ASPSupport.waitForServerAvailable(ASPSupport.java:60)
	at de.jcup.asciidoctoreditor.ASPSupport.getAspClient(ASPSupport.java:19)
	at de.jcup.asciidoctoreditor.asciidoc.AspAsciidoctorAdapter.resolveClient(AspAsciidoctorAdapter.java:68)
	at de.jcup.asciidoctoreditor.asciidoc.AspAsciidoctorAdapter.convertFile(AspAsciidoctorAdapter.java:50)
	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.convert(AsciiDoctorWrapper.java:76)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport.fullBuildTemporaryHTMLFilesAndShowAfter(AsciiDoctorEditorBuildSupport.java:219)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport.access$1(AsciiDoctorEditorBuildSupport.java:174)
	at de.jcup.asciidoctoreditor.preview.AsciiDoctorEditorBuildSupport$1.run(AsciiDoctorEditorBuildSupport.java:138)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

* Asciidoctor ASP console at Eclipse

```
>> Triggered ASP server start at port:4444
ASP: Processing file:D:\JavaPrj.Tiny.Cabin\DevOps\document\installation-guide\client-side\hello.adoc
09:39:01.949 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Starting, will create asciidoctorj instance
09:39:06.148 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Created instance
09:39:06.148 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Starting warmup phase for asciidoctor
09:39:07.023 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Warmup done
09:39:07.039 [main] INFO  d.jcup.asp.server.core.CoreAspServer - Server starting at port:4444
09:39:07.039 [main] INFO  d.jcup.asp.server.core.CoreAspServer - Server secret :xxxxxxxxxxxxxxxxxxxxxxx
>> ASP Server has been started successfully
> ASP server not available at port 4444, trigger server restart NOW
>> Triggered ASP server start at port:4445

>> ASP Server at port 4444 exited with code:Some common error happened:1
09:39:11.493 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Starting, will create asciidoctorj instance
09:39:15.481 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Created instance
09:39:15.481 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Starting warmup phase for asciidoctor
09:39:16.254 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Warmup done
09:39:16.254 [main] INFO  d.jcup.asp.server.core.CoreAspServer - Server starting at port:4445
09:39:16.269 [main] INFO  d.jcup.asp.server.core.CoreAspServer - Server secret :xxxxxxxxxxxxxxxxxxxxxxx
>> ASP Server has been started successfully
```

Here  is my environment: 

* OS: Windows 10 Home, version 1903

* JDK: 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

* Eclipse: 
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200

* Asciidoctor Editor version 2.0.0

**Comment by charleech** [comment]
### Step 1

I've a chance to start the `[Eclipse]\eclipse\plugins\de.jcup.asciidoctoreditor.libs_2.0.4\libs\asp-server-asciidoctorj-dist.jar` as the following: -

```bash
java -Dasp.server.port=9999 \
-jar path\to\asp-server-asciidoctorj-dist.jar
```
The console give us the following: -

```bash
10:46:33.028 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Starting, will create asciidoctorj instance
10:46:37.771 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Created instance
10:46:37.771 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Starting warmup phase for asciidoctor
10:46:38.508 [main] INFO  d.j.a.s.a.service.AsciidoctorService - Warmup done
10:46:38.512 [main] INFO  d.jcup.asp.server.core.CoreAspServer - Server starting at port:9999
10:46:38.519 [main] INFO  d.jcup.asp.server.core.CoreAspServer - Server secret :[SOME-BASE-64]
```

 ### Step 2

Then take the console output to file and read it with the same logic of [ExternalProcessAsciidoctorJServerLauncher Line 205](https://github.com/de-jcup/asp/blob/11aa1f3ec57f0bfc9713fff76a78cf29ec5eaa52/asp-server-asciidoctorj-launcher/src/main/java/de/jcup/asp/server/asciidoctorj/launcher/ExternalProcessAsciidoctorJServerLauncher.java#L205)

decode by using `java.util.Base64`

```java
String secret =  // use the logic from ExternalProcessAsciidoctorJServerLauncher Line 205
Base64.getDecoder().decode(secret);
```
It throws the exception as

```bash
java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 24
```

 ### Step 3

Surprisingly, If we use the  `org.apache.commons.codec.binary.Base64`, it can be decoded properly.

```java
String secret = // use the logic from ExternalProcessAsciidoctorJServerLauncher Line 205
byte[] buff = org.apache.commons.codec.binary.Base64.decodeBase64(secretKey);
```
 ### Step 3-A

The dig deeper

```java
String newSecret1 = org.apache.commons.codec.binary.Base64.encodeBase64String(buff);
String newSecret2 =  java.util.Base64.getEncoder().encodeToString(buff)
```
The `newSecret1` and  `newSecret2` is not equal to `secret`, since the `secret` contains `new line` character.

### Suspected

Then try to trim the `secret ` by using `secret.trim()`, the `java.util.Base64.getDecoder().decode(secret)` is worked properly.

I hope this information may be useful.

**Comment by de-jcup** [comment]
Thanx for reporting.

Have same problem on windows 7 - seems to be console output reading returns at windows `\r\n` instead `\n` ... So trim of whitespace is necessary to get rid of the problem. 
_(Using Linux I do not get the problem... Have changed deployment checks so will test next time Linux and Windows...)_

Will be fixed.

**Comment by de-jcup** [comment]
Hello @charleech I just released Version 2.0.2 on eclipse marketplace. The plugin does now provide the workaround with key trim, but it will be fixed in ASP in future (see https://github.com/de-jcup/asp/issues/21 )

**Comment by charleech** [comment]
Hi @de-jcup 

I've updated to version `2.0.2` and can confirm that the issue has been resolve.

Thank you very much.

**Comment by BhuvaneshwarBharathiya** [comment]
Hello @de-jcup 
I used version 3.1.1 on windows 12,  I encountered same issue.
