### ISSUE TITLE
preview stopped working with latest eclipse

### ISSUE THREAD

**Issue by spamdaemon** [de-jcup/eclipse-asciidoctor-editor#263]
All of a sudden I keep getting this error about input and output files being the same:

```
ASP: Processing file:/home/str/documentation/docs/dsl/examples/overview.adoc
ASP client->server :{"version":"0.0.0","command":"is_alive"}
ASP server->client :{}
ASP client->server :{"version":"0.0.0","command":"convert_file","source_filepath":"/tmp/asciidoctor-editor-temp/project_documentation-371305743/298991257_hidden-editorfile_overview.adoc","options":{"header_footer":false,"to_dir":"/tmp/asciidoctor-editor-temp/project_documentation-371305743","sourcemap":"true","base_dir":"/home/str/documentation","safe":0,"backend":"html5","attributes":{"showtitle":true,"source-highlighter":"rouge","eclipse-editor-basedir":"/home/str/documentation","icons":"font","coderay-css":"style","env":"eclipse","env-eclipse":"","appendix-caption":"附錄","appendix-refsig":"{appendix-caption}","blockdiag-fontpath":"/path/to/font.ttf <1>","caution-caption":":fire:","chapter-label":"Kapitel","chapter-refsig":"{chapter-label}","check":"icon:check[]","conum-guard-yaml":"#","description":"Asciidoctor 的 扩展 Asciidoctor Diagram 的说明文档。","doctype":"book","example-caption":"示例","figure-caption":"圖表","icon-set":"pf","idseparator":"-","image-uri-screenshot":"https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/screenshot.png","important-caption":":exclamation:","language":"{source-language}","last-update-label":"最後更新","man manual":"Asciidoctor Manual","man source":"Asciidoctor {release-version}","note-caption":":paperclip:","outfilesuffix":".adoc","page-background-image":"image:bg.png[pdfwidth=50%,position=bottom right]","page-layout":"base","part-label":"Del","part-refsig":"{part-label}","plantumlconfig":"plantuml.cfg","project-handle":"asciidoctor-pdf","project-name":"Asciidoctor PDF","release-version":"1.5.0.beta.5","rouge-style":"custom","section-refsig":"Avsnitt","sectnumlevels":"6","source-language":"asciidoc","star":"&#9733;","table-caption":"表格","tip-caption":":bulb:","toc-title":"目錄","toclevels":"1","translators":"D瓜哥","untitled-label":"暫無標題","uri-a2s":"https://github.com/dhobsd/asciitosvg","uri-actdiag":"http://blockdiag.com/en/actdiag/index.html","uri-asciidoc":"{uri-asciidoctor}/docs/what-is-asciidoc","uri-asciidoclet":"{uri-org}/asciidoclet","uri-asciidoctor":"https://asciidoctor.org","uri-asciidoctor-api":"http://asciidoctor.org/docs/user-manual/#api","uri-asciidoctor-extensions":"http://asciidoctor.org/docs/user-manual/#extension-points","uri-asciidoctorj":"{uri-org}/asciidoctorj","uri-asciidoctorjs":"{uri-org}/asciidoctor.js","uri-blockdiag":"http://blockdiag.com","uri-changelog":"{uri-rel-file-base}CHANGELOG.adoc","uri-contribute":"{uri-rel-file-base}CONTRIBUTING.adoc","uri-contributors":"{uri-repo}/graphs/contributors","uri-convert-doc":"{uri-docs}/convert-documents","uri-discuss":"http://discuss.asciidoctor.org","uri-ditaa":"http://ditaa.sourceforge.net/","uri-docs":"{uri-project}/docs","uri-dot":"http://www.graphviz.org/content/dot-language","uri-erd":"https://github.com/BurntSushi/erd","uri-foundation":"https://foundation.zurb.com","uri-freesoftware":"https://www.gnu.org/philosophy/free-sw.html","uri-gem":"https://rubygems.org/gems/asciidoctor","uri-gitscm-repo":"https://github.com/git/git-scm.com","uri-gradle-plugin":"{uri-org}/asciidoctor-gradle-plugin","uri-graphviz":"http://www.graphviz.org","uri-imagemagick":"http://www.imagemagick.org","uri-install-docker":"https://github.com/asciidoctor/docker-asciidoctor","uri-install-macos-doc":"{uri-docs}/install-asciidoctor-macos","uri-install-osx-doc":"{uri-docs}/install-asciidoctor-macosx","uri-irc":"irc://irc.freenode.org/#asciidoctor","uri-issues":"{uri-repo}/issues","uri-java":"http://java.sun.com","uri-license":"{uri-rel-file-base}LICENSE","uri-manpage":"{uri-project}/man/asciidoctor","uri-maven-plugin":"{uri-org}/asciidoctor-maven-plugin","uri-mermaid":"http://knsv.github.io/mermaid/","uri-mscgen":"http://www.mcternan.me.uk/mscgen/","uri-news":"{uri-project}/news","uri-nomnoml":"http://nomnoml.com","uri-nwdiag":"http://blockdiag.com/en/nwdiag/index.html","uri-opal":"https://opalrb.com","uri-org":"https://github.com/asciidoctor","uri-packetdiag":"http://blockdiag.com/en/nwdiag/index.html","uri-phantomjs":"http://phantomjs.org","uri-plantuml":"http://plantuml.sourceforge.net","uri-project":"https://asciidoctor.org","uri-prototype":"{uri-gitscm-repo}/commits/master/lib/asciidoc.rb","uri-py-plantuml":"https://code.google.com/p/asciidoc-plantuml/","uri-rackdiag":"http://blockdiag.com/en/nwdiag/index.html","uri-rel-file-base":"{uri-repo}/blob/master/","uri-rel-tree-base":"{uri-repo}/tree/master/","uri-render-doc":"{uri-docs}/render-documents","uri-repo":"https://github.com/asciidoctor/asciidoctor-pdf","uri-ruby":"https://www.ruby-lang.org","uri-rubygem":"https://rubygems.org/gems/asciidoctor","uri-seqdiag":"http://blockdiag.com/en/seqdiag/index.html","uri-shaape":"https://github.com/christiangoltz/shaape","uri-svgbob":"https://github.com/ivanceras/svgbobrus","uri-syntrax":"https://kevinpt.github.io/syntrax/","uri-tests":"{uri-rel-tree-base}test","uri-themes-doc":"{uri-docs}/produce-custom-themes-using-asciidoctor-stylesheet-factory","uri-tilt":"https://github.com/rtomayko/tilt","uri-umlet":"http://www.umlet.com/","uri-user-manual":"{uri-docs}/user-manual","uri-vega":"https://vega.github.io/vega/","uri-vegalite":"https://vega.github.io/vega-lite/","uri-wavedrom":"http://wavedrom.com","uri-wavedromcli":"https://github.com/wavedrom/cli","uri-wavedromeditor":"https://github.com/wavedrom/wavedrom.github.io/releases","uri-what-is-asciidoc":"{uri-docs}/what-is-asciidoc","url-asciidoctor":"http://asciidoctor.org","url-asciidoctor-mathematical":"https://github.com/asciidoctor/asciidoctor-mathematical","url-docs":"https://asciidoctor.org/docs","url-fontforge":"https://fontforge.github.io/en-US/","url-fontforge-scripting":"https://fontforge.github.io/en-US/documentation/scripting/","url-gem":"http://rubygems.org/gems/asciidoctor-pdf","url-graphicsmagick":"http://www.graphicsmagick.org","url-prawn":"http://prawnpdf.org","url-prawn-gmagick":"https://github.com/packetmonkey/prawn-gmagick","url-prawn-svg":"https://github.com/mogest/prawn-svg","url-project":"https://github.com/asciidoctor/asciidoctor-pdf","url-project-issues":"{url-project-repo}/issues","url-project-list":"http://discuss.asciidoctor.org","url-project-repo":"{url-project}","url-rvm":"http://rvm.io","version-label":"版本","warning-caption":":warning:","window":"_blank","imagesoutdir":"/tmp/asciidoctor-editor-temp/project_documentation-371305743/images","imagesdir":"/tmp/asciidoctor-editor-temp/project_documentation-371305743/images","outdir":"/tmp/asciidoctor-editor-temp/project_documentation-371305743"}}}
Sep 25, 2019 5:45:14 AM org.asciidoctor.jruby.internal.JRubyAsciidoctor convertFile
SEVERE: (IOError) input file and output file cannot be the same: /tmp/asciidoctor-editor-temp/project_documentation-371305743/298991257_hidden-editorfile_overview.adoc
05:45:14.195 [main] ERROR d.j.a.s.a.s.ConvertLocalFileServiceImpl - Was not able to convert
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.IOError: (IOError) input file and output file cannot be the same: /tmp/asciidoctor-editor-temp/project_documentation-371305743/298991257_hidden-editorfile_overview.adoc
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:379)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:350)
	at de.jcup.asp.server.asciidoctorj.service.ConvertLocalFileServiceImpl.handleConvert(ConvertLocalFileServiceImpl.java:81)
	at de.jcup.asp.server.asciidoctorj.service.ConvertLocalFileServiceImpl.convertFile(ConvertLocalFileServiceImpl.java:55)
	at de.jcup.asp.server.asciidoctorj.AsciiDoctorJServerClientRequestHandler.handleRequest(AsciiDoctorJServerClientRequestHandler.java:50)
	at de.jcup.asp.server.core.CoreAspServer.waitForClient(CoreAspServer.java:121)
	at de.jcup.asp.server.core.CoreAspServer.start(CoreAspServer.java:81)
	at de.jcup.asp.server.asciidoctorj.AsciidoctorJServer.start(AsciidoctorJServer.java:40)
	at de.jcup.asp.server.asciidoctorj.AsciidoctorJServerApplication.main(AsciidoctorJServerApplication.java:46)
Caused by: org.jruby.exceptions.IOError: (IOError) input file and output file cannot be the same: /tmp/asciidoctor-editor-temp/project_documentation-371305743/298991257_hidden-editorfile_overview.adoc
	at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/convert.rb:103)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/convert.rb:183)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1157)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/convert.rb:183)
ASP server->client :{"version":"1.0.0","error":"org.jruby.exceptions.IOError: (IOError) input file and output file cannot be the same: /tmp/asciidoctor-editor-temp/project_documentation-371305743/298991257_hidden-editorfile_overview.adoc"}
Command convert_file failed.Failed:org.jruby.exceptions.IOError: (IOError) input file and output file cannot be the same: /tmp/asciidoctor-editor-temp/project_documentation-371305743/298991257_hidden-editorfile_overview.adoc
```

**Comment by de-jcup** [comment]
Hello @spamdaemon , I tried out with new eclipse (using clean package and installed from eclipse marketplace)

```asciidoc
== Testcase

Test for 
https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/263

=== Eclipse version 

[options="header",cols="1,8"]
|===
|Key   |Info  
//----------------------
|Variant   |Eclipse IDE for Java Developers   
|Version   |2019-09 R (4.13.0)   
|Build     |20190917-1200         
|===
```

I got following output:

![image](https://user-images.githubusercontent.com/11644753/65646052-0201c800-dffa-11e9-8938-c0551221d935.png)

So it works with Linux, newest eclipse and ASP enabled at my machine.

**Comment by de-jcup** [comment]
Maybe you could create a eclipse testproject having your described failure and attach it as an zip file to this issue? Would be easier to give support... 

Best wishes
Albert

**Comment by Jeremy42** [comment]
I've encountered the same problem today, however after a few hours of pain trying to get the AsciiDoctor Ruby Gem installed on WIndows 10 and referenced from the Eclipse AsciiDoctor Preferences, I eventually found that if you have any file with an "adoc" extension in the same folder as your eclipse ",project" file then you get the "... input and output can't be the same ..." errors no matter where in the folder hierarchy the file you're trying to preview is !!!

Thanks for a great tool though, much appreciated.

**Comment by Jeremy42** [comment]
Hang on, there's more to it than that ...

**Comment by Jeremy42** [comment]
... it seems it's nothing to do with the same folder as ".project",
instead it seems to be specifically the header line
":outfilesuffix: .adoc"
as found in "README.adoc" from https://github.com/asciidoctor/asciidoctor.git.

On first load it renders the preview fine but if you press the "Rebuild Asciidoc preview content (F5)" button then it fails and subsequent refreshes of other "adoc" files also fail.

Delete the file from the project and the other "adoc" files will refresh again just fine.

Over to you Albert
Many thanks
Jeremy

**Comment by Jeremy42** [comment]
Using this instead seems to fix it :-

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

**Comment by de-jcup** [comment]
@spamdaemon - have you still the problem or can we close this issue?
