### ISSUE TITLE
Image generation always timing out.

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#358]
This issue is a copy from eclipse marketplace: https://marketplace.eclipse.org/comment/7564#comment-7564

---
I have installed the asciidoctor plugin on a second machine. Before I did I installed the GraphViz stuff and tested it and its working (you see - I learned my lesson with this plugin).

But now I have another most annoying effect:

If I create a testfile containing just 

```asciidoc
@startuml
testdot
@enduml
```
and save it then the plugin kicks in and a few seconds later I get an "image" that reads:

```
PlantUML verson 1.2021.2 (Sun Mar 07 12:10:27 CET 2021)
Dot version: dot - graphviz version 2.47.1 (20210417.1919)
Installation seems OK. File generation OK
```
So, the config seems to be working.

However, as soon as I save a file that contains more than just 2-3 components or classes then the image generation always hangs "forever" (i.e. a minute or so) and all I ever get is a message like:

```
Preview file generation timed out, so preview not available at: 
C:\Users\mmo\AppData\Local\Temp\asciidoctor-editor-temp\project_example_app-174616751\-1369575984_internal_mainclasses.html
```

My Laptop is pretty fast (i7 CPU (10th gen), 16GB RAM, 1TB SSD, etc.) so I doubt that a simple picture with maybe 10 rectangles can really be taking so long that the graph generation times out. 
Any idea what could cause this? 

This is on eclipse 2021-03.

**Comment by de-jcup** [comment]
Tried with eclipse 2021-03:

![image](https://user-images.githubusercontent.com/11644753/119276013-aba6bb80-bc18-11eb-8443-5ddad528afb5.png)

**Comment by de-jcup** [comment]
## Reproduce mentioned problems
Used Eclipse 2021-03 on Linux (ubuntu based):

Tried attached `puml` file [classdiagram-test.puml.zip](https://github.com/de-jcup/eclipse-asciidoctor-editor/files/6528908/classdiagram-test.puml.zip)
 on my Linux machine - initial rendering was very fast.

![image](https://user-images.githubusercontent.com/11644753/119276139-72228000-bc19-11eb-8b30-96c0bda91f46.png)

Then I removed all temporary files from disk and tried again - it took a quite long time and then the preview file rendering timed out:

![image](https://user-images.githubusercontent.com/11644753/119276447-9468cd80-bc1a-11eb-937d-45a02d916670.png)

## Error log
I found message : "Was not able to write transformed file:classdiagram-test.puml" with stacktrace:
```
java.io.FileNotFoundException: /tmp/asciidoctor-editor-temp/project_temp56910993/-10935349_classdiagram-test.puml (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at de.jcup.asciidoctoreditor.asciidoc.AsciiDocStringUtils.writeTextToUTF8File(AsciiDocStringUtils.java:162)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.createTransformedTempfile(AsciidocEditorPreviewBuildRunnnable.java:377)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.createTransformedTempFileFromEditorFile(AsciidocEditorPreviewBuildRunnnable.java:364)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.createTransformedTempFileOrNull(AsciidocEditorPreviewBuildRunnnable.java:271)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.buildHTMLPreviewFile(AsciidocEditorPreviewBuildRunnnable.java:113)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.run(AsciidocEditorPreviewBuildRunnnable.java:83)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by de-jcup** [comment]
## Former commit
After last commit the "file not found" problem will no longer appear.

## Still problems when editor new created
Setup: In preferences default preview layout is set to "Vertical"

When 
-  removing the temp files (forcing `plantuml` to do some renderings without cache) 
-  close opened editor
-  opening the plantuml file in editor again, the preview dialog is still open and the "preview generation timed out" 
   appears 
   * /tmp/asciidoctor-editor-temp/project_testscripts-2091783503/-1884445895_internal_testcase.html is NOT created
   * /tmp/asciidoctor-editor-temp/project_testscripts-2091783503/ -1884445895_preview_testcase.html  is created
   * pressing F5 recreates the missing HTML file
   * /tmp/asciidoctor-editor-temp/project_testscripts-2091783503/-1884445895_internal_testcase.html is available

So F5 and initial startup do different things here.

**Comment by de-jcup** [comment]
## What about .adoc files at all?
Tested with `test.adoc`: same problem  - initally the editor does only provide external preview files  but not the internal ones! So this, what is mentioned inside #357 !

## Current preferences
![image](https://user-images.githubusercontent.com/11644753/119277845-3213cb00-bc22-11eb-8fd7-238cedd9c69b.png)
