### ISSUE TITLE
java.lang.NullPointerException in de.jcup.asciidoctoreditor.asciidoc.AsiidocConfigFileSupport.calculateResolvedMap(

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#385]
Happens during save:

java.lang.NullPointerException: Cannot invoke "de.jcup.asciidoctoreditor.asciidoc.AsiidocConfigFileSupport.calculateResolvedMap(java.util.Map, java.util.List)" because "support" is null
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorAttributesProvider.resolveAttributes(AsciiDoctorAttributesProvider.java:106)
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorAttributesProvider.getCachedAttributes(AsciiDoctorAttributesProvider.java:94)
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorImageProvider.resolveImagesDirPath(AsciiDoctorImageProvider.java:138)
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorImageProvider.getCachedSourceImagesPath(AsciiDoctorImageProvider.java:92)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor.getImagesPathOrNull(AsciiDoctorEditor.java:520)
	at de.jcup.asciidoctoreditor.AsciidoctorEditorOutlineSupport.validate(AsciidoctorEditorOutlineSupport.java:178)
	at de.jcup.asciidoctoreditor.AsciidoctorEditorOutlineSupport.lambda$0(AsciidoctorEditorOutlineSupport.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

**Comment by vogella** [comment]
Maybe follow-up of:

java.lang.IllegalArgumentException: Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:137)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:401)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:66)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:311)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:225)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:392)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:413)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:160)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:251)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by de-jcup** [comment]
@vogella : the second callstack has nothing to do with the first one.
The problem is here:
https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/35705dbb50187fb9cdc51575582936586678e456/asciidoctor-editor-plugin/src/main/java/de/jcup/asciidoctoreditor/provider/AsciiDoctorAttributesProvider.java#L105-L106

The returned support is null
And the support is only set by these calls:
![image](https://user-images.githubusercontent.com/11644753/154854368-2658a5f1-33d6-464a-8b19-1e113bde147f.png)

So this happens when no HTML view or pdf rendering has been done.

**Comment by de-jcup** [comment]
A temporary workaround should be to either enable HTML preview or to turn off image validation.

**Comment by de-jcup** [comment]
Was able to reprocude. Happens only (but always) when preview is disabled. Editor works at all, but at least image validation will not work  - because of exception.

Will fix it.
