### ISSUE TITLE
[Windows] Attempted to beginRule: MultiRule[], does not match outer scope rule: R/

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#425]
Using latest release I still get a lot of  the following errors in Windows.

@de-jcup didn't you fix that in another issue?

java.lang.IllegalArgumentException: Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:138)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:402)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:66)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by vogella** [comment]
This bug makes is really annoying to use the plug-in in Windows. I'm getting this error on every save.

**Comment by de-jcup** [comment]
@vogella : Sorry for the late response - I will take a look.

## Analyze/Try to reproduce

I tried with
- Windows 10
- Eclipse 2021-12
- Asciidoctor Editor plugin Version 2.5.1
- Java Versoin 17.0.1 (Eclipse Adoptium)

I opened multiple asciidoc files, plantuml files and also ditaa files with the asciidoctor editor and there was none of the mentioned stacktrace information inside the error log view!

## Internet search
After doing a google search, I found multiple locations where the problem also appeared (without asciidoctor editor)
I am not sure why you think the problem comes from Asciidoctor-Editor. 
Asciidoctor editor does not add any build action - when looking at the stacktace I see something like a BuildManager doing a "basicBuild". 

Here an example:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536472

## Currrent state
As long as I have not the possibility to reproduce the problem I am not able to fix it.

## Further steps
Please
- define your environment more specific
  - exact Windows Version
  - exact Eclipse Versoin
  - etc.
- provide an simple example asciidoc file inside this issue so I can reproduce the problem (best would be to add a sample project as a zip file to this issue, so I can handle encoding issues etc. as well and have the project setup etc.)

**Comment by vogella** [comment]
I don't remember if I saw this on Linux or Windows, will report once this happens again.

**Comment by vogella** [comment]
Happens for me on Windows all he tme if I edit one of my files. Here is an example content:

````
== Performing the rebase operation via the Eclipse IDE

=== Rebasing a branch onto another

Now do a rebase of the conflicting commit instead of a merge.
Checkout the branch  `addDivideOperation` via right-mouse in the History and by selecting _Check out_.
		
In the History View, select _Rebase HEAD on_ from the context menu on the second one of the branches which has a conflict, e.g. as it modified the same file in the same line.

* `addMultiplyOperation` or
* `addMultiplyOperationConflict` - this branch is only available if you did the optional part of the merge with Eclipse exercise.

				
image::rebase.png[Rebase]

				
The rebase stops because of a conflict. You see a dialog:

image::rebase-with-conflicts.png[Rebase]			
				
Click _Proceed_ to start the merge tool.
				
Click _OK_ to start conflict resolution (using pre-merged option).
						
image::merge-tool-2.png[Merge Tool]				
				
Edit the left side until you are happy with the change and save.
				
image::merge-tool-resolved-conflict-2.png[Merge Tool with resolved conflict] 						
				
Use the Git Staging View to stage the changes by drag and drop.
				
				
In the Repositories View select your repository and click menu:Rebase[Continue].

				
image::rebase-continue.png[Rebase Continue]					
				

=== Validate result 
				
Now the history view should look similar to the following picture.

image::history-view-5.png[History View]			
				
				
Note that there is a reference called `ORIG_HEAD` pointing to the commit which was checked out before the rebase operation. 
You may revert the rebase operation with reset as described above.

[TIP]
====
You may hide or show the additional references such as `ORIG_HEAD`	and	`FETCH_HEAD` from the History View by selecting menu:Show[Additional Refs] in the drop-down menu.
			
image::show-additional-refs.png[Show Additional Refs]
====

````

**Comment by vogella** [comment]
Maybe it happens if the images can not be found? Frequently I add the image later.

**Comment by company-jcup** [comment]
@vogella : I tried to reproduce your problem with your Example snippet (+ not existing files ) with editor version 2.6.1 on Eclipse 2021-12 + Windows 10 - no problems: 
![image](https://user-images.githubusercontent.com/80676663/181174464-db0ce75e-7d9f-4d1b-8845-ff0e55d21919.png)

**Comment by company-jcup** [comment]
After updating my Eclipse to 2022-06 I retried to reproduce - but same situation: All is working.

**Comment by vogella** [comment]
This is floating my error log:

![Screenshot_2](https://github.com/de-jcup/eclipse-asciidoctor-editor/assets/139910/75239119-afea-40a2-bbde-ccf4ba8a3424)
