### ISSUE TITLE
error ducring preview generation :  (ESRCH) No such process - asciidoctor:

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#440]
### Discussed in https://github.com/de-jcup/eclipse-asciidoctor-editor/discussions/426

<div type='discussions-op-text'>

<sup>Originally posted by **harlock001** May 17, 2022</sup>
Hi 

during the generation of the preview using the embedded ASP, the error below is generated. I changed the path name to reduce its length and it seems to have fixed the problem.
Is this the true issue? If yes, is it possible to configure the location of the temp folder in a configuration file and where?

Thank you and kind regards,

`13:41:04.612 [main] ERROR d.j.a.s.a.s.ConvertLocalFileServiceImpl - Was not able to convert
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.SystemCallError: (ESRCH) No such process - asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - No such process - C:\Users\xxxx\AppData\Local\Temp\2\asciidoctor-editor-temp\project_xxxxxxxxxxxxxxxxx\48693eba2b1c88dd10be2fd63f1a9cd2dd354c1787ed6df9ad99d3197b0ae698\9915f15eb981730d73b6a95133856356ba9f8a2b9c76a5883a7ed86a1dfcbaf1_hidden-editorfile_xxxxxxxxxxxxxxxxx.adoc
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:402)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:416)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:411)
	at de.jcup.asp.server.asciidoctorj.service.ConvertLocalFileServiceImpl.handleConvert(ConvertLocalFileServiceImpl.java:77)
	at de.jcup.asp.server.asciidoctorj.service.ConvertLocalFileServiceImpl.convertFile(ConvertLocalFileServiceImpl.java:58)
	at de.jcup.asp.server.asciidoctorj.AsciiDoctorJServerClientRequestHandler.handleRequest(AsciiDoctorJServerClientRequestHandler.java:47)
	at de.jcup.asp.server.core.CoreAspServer.waitForClient(CoreAspServer.java:121)
	at de.jcup.asp.server.core.CoreAspServer.start(CoreAspServer.java:81)
	at de.jcup.asp.server.asciidoctorj.AsciidoctorJServer.start(AsciidoctorJServer.java:40)
	at de.jcup.asp.server.asciidoctorj.AsciidoctorJServerApplication.main(AsciidoctorJServerApplication.java:46)
Caused by: org.jruby.exceptions.SystemCallError: (ESRCH) No such process - asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - No such process - C:\Users\xxxx\AppData\Local\Temp\2\asciidoctor-editor-temp\project_xxxxxxxxxxxxxxxxx\48693eba2b1c88dd10be2fd63f1a9cd2dd354c1787ed6df9ad99d3197b0ae698\9915f15eb981730d73b6a95133856356ba9f8a2b9c76a5883a7ed86a1dfcbaf1_hidden-editorfile_xxxxxxxxxxxxxxxxx.adoc
	at RUBY.load(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/load.rb:104)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:78)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1158)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190)
`</div>

**Comment by de-jcup** [comment]
@harlock001 : The long path names should no longer be a problem at all - it should be fixed with 2.5.1 already (see #414) 

Yesterday  I released v2.6.1 on eclipse marketplace. It does now store the temporary files at a user home location (for security reasons) and has also an integrated auto cleanup mechansim of those files. I tested 2.6.1 with Windows 10 and all is working fine.

Please give me feedback if you have no problems when using 2.6.1 - if so, I will close the issue.

**Comment by harlock001** [comment]
indeed, this problem is fixed in version 2.5.1.
Thank you.
